### ISSUE TITLE
TextAfter в subsense

### ISSUE THREAD

**Issue by jvsntsn** [abaevdict/abaevdict#10]
![image](https://user-images.githubusercontent.com/48504970/55883410-f5ee8f00-5bae-11e9-9bd3-87fc2135dad1.png)

**Comment by obelyaev** [comment]
Просто сделать TextAfter в SubSense.

**Comment by obelyaev** [comment]
По идее здесь просится PostComment, но нынешняя структура не позволяет нормально это реализовать. Пока можно писать это в скобках после глоссы; будет внутри марровских кавычек, но это не так страшно.

**Comment by obelyaev** [comment]
В итоге поменял-таки структуру, так что всё как надо :)
