### ISSUE TITLE
TxAfter после Example?

### ISSUE THREAD

**Issue by solanum-tuberosum** [abaevdict/abaevdict#11]
![image](https://user-images.githubusercontent.com/13102259/55883887-c68c5200-5baf-11e9-840b-cc3e829a349c.png)

**Comment by solanum-tuberosum** [comment]
![image](https://user-images.githubusercontent.com/13102259/55884087-1e2abd80-5bb0-11e9-846d-576861cbbebc.png)

**Comment by obelyaev** [comment]
Возможно, разрешить добавлять Collocation как элемент ExampleGroup.

**Comment by solanum-tuberosum** [comment]
![image](https://user-images.githubusercontent.com/13102259/55886748-fb4ed800-5bb4-11e9-8094-a08d80b5087c.png)

**Comment by obelyaev** [comment]
PostSubentryGroup для групп "коллокаций", появляющихся после примеров.

В последнем скриншоте начальное "и (" похоже на опечатку; в целом такое тире после "коллокации" описывается как PostComment внутри Subentry.
