### ISSUE TITLE
Нечто после леммы в скобочках нежирное

### ISSUE THREAD

**Issue by solanum-tuberosum** [abaevdict/abaevdict#12]
![image](https://user-images.githubusercontent.com/13102259/55885314-65b24900-5bb2-11e9-8ee5-a54a48d79a0c.png)

**Comment by solanum-tuberosum** [comment]
![image](https://user-images.githubusercontent.com/13102259/55885433-97c3ab00-5bb2-11e9-952d-81f1b339384d.png)

**Comment by obelyaev** [comment]
Это не восклицательный знак, если что.

**Comment by obelyaev** [comment]
Нужно для этого ввести какое-то поле.

**Comment by solanum-tuberosum** [comment]
А здесь жирное!
![image](https://user-images.githubusercontent.com/13102259/55887153-b11a2680-5bb5-11e9-9668-f87710a390d9.png)

**Comment by solanum-tuberosum** [comment]
!!!

![image](https://user-images.githubusercontent.com/13102259/55891201-d2324580-5bbc-11e9-9bae-0d2c10409eda.png)

**Comment by jvsntsn** [comment]
![image](https://user-images.githubusercontent.com/48504970/55892575-36560900-5bbf-11e9-9920-dd063cbcebd9.png)

**Comment by obelyaev** [comment]
Первые три примера решаются через параметр InParentheses у LemmaVariant (они, правда, станут жирными, но это нестрашно, мне кажется: я всё равно никакой логики здесь не вижу). Для последнего я добавил поле Type.

С kʼūlæg хуже. Пока реализовал это через тот же LemmaVariant в скобках с добавлением PreComment и PostComment, но это явный костыль, конечно. Будем надеяться, что таких случаев немного :)
