### ISSUE TITLE
Еще что-то новое для структуры?

### ISSUE THREAD

**Issue by jvsntsn** [abaevdict/abaevdict#13]
В начале статьи после значений.
![image](https://user-images.githubusercontent.com/48504970/55885498-bb86f100-5bb2-11e9-95d5-d5dbbf2e45b9.png)

**Comment by obelyaev** [comment]
См. #9.

**Comment by obelyaev** [comment]
PostComment к SenseGroup, затем две PreSubentryGroup, затем ExampleGroup.
