### ISSUE TITLE
TxBefore в Cit?

### ISSUE THREAD

**Issue by solanum-tuberosum** [abaevdict/abaevdict#14]
![image](https://user-images.githubusercontent.com/13102259/55886493-867b9e00-5bb4-11e9-8fbd-764e6c816759.png)

**Comment by obelyaev** [comment]
да, это нужно сделать

**Comment by obelyaev** [comment]
Добавил PreComment в число допустимых элементов cit. По идее, должно хватить. Не могу, к сожалению, реализовать, потому что не знаю, к какой лексеме эта этимология.
