### ISSUE TITLE
Ссылки на литературу и перекрёстные ссылки в Sense?

### ISSUE THREAD

**Issue by solanum-tuberosum** [abaevdict/abaevdict#15]
![image](https://user-images.githubusercontent.com/13102259/55886667-dce8dc80-5bb4-11e9-8d8d-5da4896069dc.png)

**Comment by solanum-tuberosum** [comment]
И вот еще, но здесь в Definition
![image](https://user-images.githubusercontent.com/13102259/55886871-32bd8480-5bb5-11e9-8635-5a9cbf2cc0c3.png)

**Comment by obelyaev** [comment]
значит, надо сделать

**Comment by obelyaev** [comment]
В дефиниции вы вроде бы можете добавлять references.

**Comment by solanum-tuberosum** [comment]
![image](https://user-images.githubusercontent.com/13102259/55887057-8760ff80-5bb5-11e9-8b1d-a376965a1fa8.png)

**Comment by solanum-tuberosum** [comment]
И перекрестные ссылки в Sense?
![image](https://user-images.githubusercontent.com/13102259/55887275-e6bf0f80-5bb5-11e9-8a7e-c090057fcdee.png)

**Comment by obelyaev** [comment]
PostComment к Sense, а там уже в поле Text_RU/EN можно делать что угодно.
