### ISSUE TITLE
TxAfter после словосочетания, но до перевода в Collocation

### ISSUE THREAD

**Issue by solanum-tuberosum** [abaevdict/abaevdict#18]
![image](https://user-images.githubusercontent.com/13102259/55888330-d871f300-5bb7-11e9-9674-39efdbd1c002.png)

**Comment by obelyaev** [comment]
Может быть, перенести после перевода и сделать как TxAfter?

**Comment by solanum-tuberosum** [comment]
![image](https://user-images.githubusercontent.com/13102259/55889350-a366a000-5bb9-11e9-8cbb-b10a7ca72572.png)

**Comment by obelyaev** [comment]
ужас

**Comment by obelyaev** [comment]
PreComment к SenseGroup, CommentType = Parentheses (см. слово kar)
