### ISSUE TITLE
Проблемы с проставлением xref

### ISSUE THREAD

**Issue by jvsntsn** [abaevdict/abaevdict#20]
В этимологической части идет отсылка к основе слова, а словарная статья есть на нормальный глагол) Как быть? Не ставить xref, оставив эту странную отсылку как в оригинале, или поставить xref и сослаться на нормальную словарную статью?
![image](https://user-images.githubusercontent.com/48504970/57150041-d0335f00-6dd5-11e9-92d9-03a553ca571e.png)
![image](https://user-images.githubusercontent.com/48504970/57150066-e5a88900-6dd5-11e9-8339-3386d32a05e5.png)

**Comment by obelyaev** [comment]
Я бы сделал так: "к dar- 'держать' [см. XREF].".

Надо, кстати, придумать конвенцию, как обозначать такие вот добавления к исходному тексту. Квадратными скобками?

**Comment by obelyaev** [comment]
Давайте фигурными.
