### ISSUE TITLE
нет языка в списке

### ISSUE THREAD

**Issue by jvsntsn** [abaevdict/abaevdict#21]
Не нашла языка кхарошти в списке
![image](https://user-images.githubusercontent.com/48504970/57584767-d7e6b800-74e7-11e9-9889-9588e07ff6c7.png)

**Comment by obelyaev** [comment]
Чтобы я мог это добавить, надо, чтобы все разлогинились. Давайте завтра, когда будем встречаться.

**Comment by obelyaev** [comment]
Добавил.
