### ISSUE TITLE
два леса, оба в xref?

### ISSUE THREAD

**Issue by solanum-tuberosum** [abaevdict/abaevdict#22]
Вопрос не про структуру, а про осетинский. В первом слове на картинке есть ссылка на лес, в третьем тоже. Но они выглядят по-разному. Я пока завела оба варианта в словаре, в каждой статье на свое сослалась. Так и должно быть?
Или xref'ом надо ссылаться только на одно слово, а другое просто текстом написать?
![image](https://user-images.githubusercontent.com/13102259/57792405-95bbb180-7747-11e9-8aa2-1d75953f023b.png)

**Comment by obelyaev** [comment]
Только на одно, потому что ǧædæ — это просто дигорская форма слова qæd. Абаев ссылается на дигорский, потому что первое слово — дигорское. Я думаю, надо написать ǧædæ 'лес' (см. <xref>qæd</xref>),

**Comment by solanum-tuberosum** [comment]
У меня все равно есть еще вопрос на эту тему.
Вот в этом слове для шума указано что-то в скобках, а для мельницы нет. Но я нашла слово kwyroj, которое уже добавляла Юля (тоже мельница). Почему тогда в первом случае он пишет что-то в скобках, а во втором нет?
![image](https://user-images.githubusercontent.com/13102259/57829701-7dd04600-77b8-11e9-985e-ca29c75e981a.png)

**Comment by obelyaev** [comment]
В обоих случаях надо добавить "(см. ИРОНСКАЯ ФОРМА)".
