### ISSUE TITLE
глупый,полоумный,дуралей

### ISSUE THREAD

**Issue by solanum-tuberosum** [abaevdict/abaevdict#23]
Про это слово два маленьких вопроса.
1. Курд. в русском с большой буквы, а у нас, кажется, все всегда с маленькой в русской версии?
2. Странная ссылка на литературу... Я нашла в списке KPF, но все остальное надо же писать руками? Тогда не получается сразу после KPF поставить запятую. Забить?
![image](https://user-images.githubusercontent.com/13102259/57829828-e4556400-77b8-11e9-8ad7-ec621dd4df88.png)

**Comment by obelyaev** [comment]
1. Ну да, потому что в начале предложения. Пока сделайте с маленькой. Скорее всего у меня получится сделать большую букву в начале предложения скриптом.

2. Забить, я думаю.

**Comment by obelyaev** [comment]
Скриптом это сделать, кажется, невозможно, так что не знаю, как эту проблему решить. Может быть, спрошу у разработчиков TLex, но они не очень охотно отвечают. Пока оставим, как есть.

**Comment by solanum-tuberosum** [comment]
А не прокатит сделать что-то типа hide language, но только BigFirstLetter?))

**Comment by obelyaev** [comment]
Да, можно, кстати. Сделать? :)

**Comment by solanum-tuberosum** [comment]
Решила в таких случаях писать в русской версии текстом "Курд." и выделять жирным и делать HideLanguage, как вы где-то предложили.
