### ISSUE TITLE
SubentryGroup

### ISSUE THREAD

**Issue by solanum-tuberosum** [abaevdict/abaevdict#24]
Почему PreSubentryGroup в английской версии идет после всей статьи?
![image](https://user-images.githubusercontent.com/13102259/57834985-3bae0100-77c6-11e9-800d-0c7acfb44889.png)

**Comment by solanum-tuberosum** [comment]
Видимо, это связано вот с этим?
![image](https://user-images.githubusercontent.com/13102259/57836049-90527b80-77c8-11e9-9ca8-3fb4926c373c.png)

**Comment by obelyaev** [comment]
Нет, я думаю. не связано. просто в английском я так и не удосужился правильно настроить стили. А ошбку пишет, видимо, по какой-то другой причине… Посмотрю, в чём там дело.

**Comment by obelyaev** [comment]
Вроде бы тут всё пофиксили.
