### ISSUE TITLE
разрывное cit

### ISSUE THREAD

**Issue by solanum-tuberosum** [abaevdict/abaevdict#25]
Я не помню, обсуждали мы это или нет...
Восходит к иран. *_gavāya_-, **собственно** ‛кричать’, ‛давать знать криками (об опасности и пр.)’, ‛призывать (на помощь)’;
вот это **собственно** как вставить? (я пока забила и никак не вставила, смысла в этом слове все равно особо нет)
![image](https://user-images.githubusercontent.com/13102259/57835155-a2cbb580-77c6-11e9-8be2-3f5f4bd4726b.png)

**Comment by obelyaev** [comment]
Здесь смысл в том, что у этого иранского слова есть СОБСТВЕННО значение "кричать" (основное) и производные типа "давать знать криками (о помощи)", откуда уже идёт "охранять".

Не знаю, как вставить. Тут два варианта: (1) забить и не делать у слова перевод, написав его буковками; (2) придумать что-то типа TxBefore или PreComment. Но нужно ли оно для такого случая? Их же не так много. Когда/если будем делать указатель или какую-то там базу, можно все такие случаи выловить вручную.

Кстати, звёздочку вы ведь включаете в состав <form>, да же?

**Comment by obelyaev** [comment]
В английском кстати это собственно будет стоять, скорее всего, после перевода ('to shout' (in the proper sense) или как-то так), так что там этой проблемы не будет.

**Comment by obelyaev** [comment]
Вроде бы решили по факту это игнорировать, т.е. писать перевод обычным текстом.
