### ISSUE TITLE
Список литературы

### ISSUE THREAD

**Issue by solanum-tuberosum** [abaevdict/abaevdict#26]
J. Wackernagel. Altindische Grammatik I 216 сл.)
![image](https://user-images.githubusercontent.com/13102259/58088165-bf069280-7bca-11e9-9f93-697306826fed.png)

**Comment by jvsntsn** [comment]
Есть ли в списке Gr.? В предложенном списке нашла вот такое GIPh , но я не уверена, что это оно.
![image](https://user-images.githubusercontent.com/48504970/59263590-01f7db00-8c4a-11e9-9b13-1aa28ba774f9.png)

**Comment by jvsntsn** [comment]
Также нужно добавить Путешествие Марко Поло и Одиссею)
![image](https://user-images.githubusercontent.com/48504970/59263657-281d7b00-8c4a-11e9-82d0-b5c88439751c.png)
![image](https://user-images.githubusercontent.com/48504970/59263677-34093d00-8c4a-11e9-87e1-91b0f2f379f0.png)

**Comment by solanum-tuberosum** [comment]
Еще не нашла Yast и Yasna
![image](https://user-images.githubusercontent.com/13102259/59326363-062a0400-8cef-11e9-954b-bb42feaf1d8c.png)

**Comment by solanum-tuberosum** [comment]
Сл. тоже не нашла...
![image](https://user-images.githubusercontent.com/13102259/59328645-94a18400-8cf5-11e9-8167-52ae9e3ebfd6.png)

**Comment by solanum-tuberosum** [comment]
> Есть ли в списке Gr.? В предложенном списке нашла вот такое GIPh , но я не уверена, что это оно.
> ![image](https://user-images.githubusercontent.com/48504970/59263590-01f7db00-8c4a-11e9-9b13-1aa28ba774f9.png)

У меня тоже встретилось Gr.
![image](https://user-images.githubusercontent.com/13102259/59330267-ad139d80-8cf9-11e9-8915-160372703ebf.png)

**Comment by jvsntsn** [comment]
Вот этого товарища тоже нет:
![image](https://user-images.githubusercontent.com/48504970/59333631-67f36980-8d01-11e9-8754-4198b21e9456.png)

**Comment by jvsntsn** [comment]
Еще вот этого товарища нет
![image](https://user-images.githubusercontent.com/48504970/59355148-28dc0d00-8d2f-11e9-956f-56b3b671ef7d.png)

**Comment by obelyaev** [comment]
> Еще не нашла Yast и Yasna
> ![image](https://user-images.githubusercontent.com/13102259/59326363-062a0400-8cef-11e9-954b-bb42feaf1d8c.png)

Только Yašt (там даже видно у Абаева)

**Comment by obelyaev** [comment]
> Есть ли в списке Gr.? В предложенном списке нашла вот такое GIPh , но я не уверена, что это оно.
> ![image](https://user-images.githubusercontent.com/48504970/59263590-01f7db00-8c4a-11e9-9b13-1aa28ba774f9.png)

Это часть библиографической ссылки на Миллера (что-то немецкое, не могу расшифровать :) ).

**Comment by obelyaev** [comment]
> Сл. тоже не нашла...
> ![image](https://user-images.githubusercontent.com/13102259/59328645-94a18400-8cf5-11e9-8167-52ae9e3ebfd6.png)

А вот это осетинский источник. См. #41 . Добавил возможность добавить элемент Source внутри form.

**Comment by obelyaev** [comment]
Остальных людей добавил.
