### ISSUE TITLE
PreComment в Example?

### ISSUE THREAD

**Issue by jvsntsn** [abaevdict/abaevdict#27]
Встретилась вот такая помета перед примером, хотела добавить ее прекомментом, но не нашла его в example...
![image](https://user-images.githubusercontent.com/48504970/59030144-d0a59680-8868-11e9-86e9-643bd2e198e3.png)

**Comment by obelyaev** [comment]
Добавить в Type, пусть пока будет в скобках, если будет без скобок, добавим ещё одно.

**Comment by obelyaev** [comment]
Наверное, учитывая то, что бывают диалекты в скобках, лучше сделать для них и подобных вещей отдельное поле.

**Comment by obelyaev** [comment]
Всё-таки сделал отдельное поле именно для диалектов с открытым списком, чтобы единообразно их переводить. Для комментариев в свободной форме лучше сделать PreComment
