### ISSUE TITLE
недостающие языки в cit

### ISSUE THREAD

**Issue by jvsntsn** [abaevdict/abaevdict#28]
Нужно добавить мансийский язык
![image](https://user-images.githubusercontent.com/48504970/59099242-470acd00-892b-11e9-98ae-55f2c318c3e8.png)

**Comment by jvsntsn** [comment]
еще хорватский)

И еще тогда сразу вопрос: у Абаева тут языки идут не по алфавитному порядку, а у нас если отмечать все языки в одном cit'е, они будут идти по алфавиту. Видимо, придется немного отклониться от первоисточника?
![image](https://user-images.githubusercontent.com/48504970/59148375-ed7cce00-8a10-11e9-99fb-3e30e3f1c32e.png)

**Comment by obelyaev** [comment]
Лучше оставить порядок как есть, мы не сможем учесть все возможные варианты.

**Comment by obelyaev** [comment]
Добавил недостающие языки, заодно нашёл способ сортировать несколько языков (теперь они отображаются в том порядке, в котором их отметили).
