### ISSUE TITLE
Много вопросов про ᵆǧzalyn

### ISSUE THREAD

**Issue by solanum-tuberosum** [abaevdict/abaevdict#30]
1. Если (J. Wackernagel. Altindische Grammatik I 216 сл.)) встречается в этом томе только один раз, то надо ли вставлять его в литературу и делать на него ссылку?
2. Снова вопрос про ᵆ --- если я на само слово не делаю перекрестную ссылку, а на второе слово делаю, то из-за ᵆ они выглядят по-разному. В какую сторону стоит унифицировать?
![image](https://user-images.githubusercontent.com/13102259/59282680-fa4c2c80-8c71-11e9-9e7c-8720173338ac.png)
3. На картинке выше ссылка (Коста 44). Я не нашла в списке просто Коста, нашла только Коста. Этн. Это то же самое или другое?
4. Тоже на картинке выше ссылка Вс. Миллер. ОЭ. В списке нашла в обратном порядке: Миллер Вс. ОЭ. Мб унифицировать тоже и сделать как у Абаева?
5. Глобальный вопрос про перевод. Абаев рассуждает, что расхождение значений 'сыпать' и 'лить' кажущееся. В английском, насколько я понимаю, это все один и тот же pour. Будет странно писать, что расхождение значений 'pour' and 'pour' кажущееся. И даже 'pour (sand)' и 'pour (water)' тоже будет выглядеть странно...

**Comment by obelyaev** [comment]
1. Добавлю его, как и Марко Поло.

2. См. #29 

3. Предусмотреть возможность ссылки на осетинские источники в этимологии.

4. Поменять в списке.

5. Подумаю, что с этим делать. ПРОВЕРИТЬ ВЕСЬ ПЕРЕВОД ЭТОЙ СТАТЬИ

**Comment by obelyaev** [comment]
1. Добавил.

2. Пока что унифицируем в сторону начальной лягушки.

3. Добавил возможность добавить Source внутри form.

4. Поменял порядок в списке.

5. Буду проверять в рамках общей ревизии текста.
