### ISSUE TITLE
MidSubentry? (ᵆgzælyn тоже коварное)

### ISSUE THREAD

**Issue by solanum-tuberosum** [abaevdict/abaevdict#31]
У слова ᵆgzælyn (стр. 537 словаря) структура выглядит как-то так: PreSubentry --> ExampleGroup --> PostSubentry --> !!ExampleGroup. Что делать?

**Comment by obelyaev** [comment]
Я наверное сделаю возможность добавлять ExampleGroup после PostSubentryGroup.

**Comment by obelyaev** [comment]
Сделал такую возможность, всё ОК (новый ExampleGroup появляется выше, но его можно сдвинуть вниз, нажав правой кнопкой и выбрав Move down).
