### ISSUE TITLE
Два xrefa в одиночестве

### ISSUE THREAD

**Issue by solanum-tuberosum** [abaevdict/abaevdict#32]
Что делать, когда в статье надо только сослаться на два слова? Если я делаю два xrefa (первый с пометой See, а второй без ничего), то они (вполне естественно) просто стоят рядом без запятой и выглядят странно.
![image](https://user-images.githubusercontent.com/13102259/59329264-2cec3880-8cf7-11e9-98a0-b9db0522b154.png)
![image](https://user-images.githubusercontent.com/13102259/59329304-42f9f900-8cf7-11e9-92e5-56ee2e71e743.png)

**Comment by obelyaev** [comment]
Сделать один xref на два слова, у обоих SEE.
