### ISSUE TITLE
PostComment к form

### ISSUE THREAD

**Issue by solanum-tuberosum** [abaevdict/abaevdict#33]
см. слово _i_
идет комментарий в скобочках
![image](https://user-images.githubusercontent.com/13102259/59351676-a0a63980-8d27-11e9-9da1-ac86f4f5b5e1.png)

**Comment by obelyaev** [comment]
Наверное, я добавлю PostComment к form, а не к cit.

**Comment by obelyaev** [comment]
Сделал возможность делать PostComment к form и исправил соответствующее слово. Правда, всё равно нельзя было сделать слова "определённый артикль" частью цитаты, приходится обычным текстом. Ради такого случая завёл отдельный атрибут def — почему бы нет; если вдруг есть такое пояснение без кавычек, можно им пользоваться.
