### ISSUE TITLE
форматирование

### ISSUE THREAD

**Issue by solanum-tuberosum** [abaevdict/abaevdict#34]
запятая
![image](https://user-images.githubusercontent.com/13102259/59351892-19a59100-8d28-11e9-91b9-2ab5f9e95cd1.png)

**Comment by jvsntsn** [comment]
в русской версии нет знаков препинания и пробела
![image](https://user-images.githubusercontent.com/48504970/59352029-61c4b380-8d28-11e9-8c8b-712b37f94c56.png)
а в английской версии стоит точка с запятой после последнего значения
![image](https://user-images.githubusercontent.com/48504970/59352085-815bdc00-8d28-11e9-98e4-1d89740d562f.png)

**Comment by solanum-tuberosum** [comment]
> в русской версии нет знаков препинания и пробела
> ![image](https://user-images.githubusercontent.com/48504970/59352029-61c4b380-8d28-11e9-8c8b-712b37f94c56.png)
> а в английской версии стоит точка с запятой после последнего значения
> ![image](https://user-images.githubusercontent.com/48504970/59352085-815bdc00-8d28-11e9-98e4-1d89740d562f.png)

у меня тоже такое
![image](https://user-images.githubusercontent.com/13102259/59352218-d0097600-8d28-11e9-8586-9860dc466590.png)

**Comment by jvsntsn** [comment]
Вот тут в английской версии в сабэнтри есть какие-то сомнительные запятые и точки, которых нет в русской версии
![image](https://user-images.githubusercontent.com/48504970/59356479-9721cf00-8d31-11e9-88ec-66687cf91fc6.png)

**Comment by obelyaev** [comment]
> в русской версии нет знаков препинания и пробела
> ![image](https://user-images.githubusercontent.com/48504970/59352029-61c4b380-8d28-11e9-8c8b-712b37f94c56.png)
> а в английской версии стоит точка с запятой после последнего значения
> ![image](https://user-images.githubusercontent.com/48504970/59352085-815bdc00-8d28-11e9-98e4-1d89740d562f.png)

Чтобы это исправить, нужно задать CommentType = Period before

**Comment by obelyaev** [comment]
> > в русской версии нет знаков препинания и пробела
> > ![image](https://user-images.githubusercontent.com/48504970/59352029-61c4b380-8d28-11e9-8c8b-712b37f94c56.png)
> > а в английской версии стоит точка с запятой после последнего значения
> > ![image](https://user-images.githubusercontent.com/48504970/59352085-815bdc00-8d28-11e9-98e4-1d89740d562f.png)
> 
> у меня тоже такое
> ![image](https://user-images.githubusercontent.com/13102259/59352218-d0097600-8d28-11e9-8586-9860dc466590.png)

Здесь надо не ставить скобки вручную, а сделать CommentType = Parentheses (исправил)

**Comment by obelyaev** [comment]
> Вот тут в английской версии в сабэнтри есть какие-то сомнительные запятые и точки, которых нет в русской версии
> ![image](https://user-images.githubusercontent.com/48504970/59356479-9721cf00-8d31-11e9-88ec-66687cf91fc6.png)

Здесь и  правда были проблемы, но при этом также много вещей, которые были сделаны, на мой взгляд, не очень корректно:

1. Штуки типа -ættæ, по-моему, всё-таки лучше включать в LemmaSign, а не делать PreComment к Sense: по смыслу это всё-таки часть слова, а не комментарий к значению (я понимаю, что тогда в LemmaSign будет запятая, но это вроде бы не так страшно).

2. Н е  н а д о  д е л а т ь  р а з р я д к у  п р о б е л а м и ! Используйте %s.

3. Несколько Subentry, разделённых точками с запятой, а не запятыми, должны каждая образовывать свою SubentryGroup. Несколько Subentry в одной SubentryGroup — это для тех (немногочисленных) случаев, когда они разделены запятыми и обычно имеют некий общий комментарий.
