### ISSUE TITLE
Ссылка на иностранные источники (с цитатами)

### ISSUE THREAD

**Issue by jvsntsn** [abaevdict/abaevdict#36]
Путешествие Марко Поло -- английская версия
The Travels of Marco Polo, the Venetian (Thomas Wright) http://public-library.uk/ebooks/60/81.pdf

**Comment by obelyaev** [comment]
Мне больше нравится перевод Генри Юла, потому что там прямо в тексте Ondanique (https://en.wikisource.org/wiki/The_Travels_of_Marco_Polo/Book_1/Chapter_17)
