### ISSUE TITLE
лол кек

### ISSUE THREAD

**Issue by jvsntsn** [abaevdict/abaevdict#37]
вот такое слово
![image](https://user-images.githubusercontent.com/48504970/59357387-735f8880-8d33-11e9-9197-ce8949292f68.png)

![image](https://user-images.githubusercontent.com/48504970/59357321-4f9c4280-8d33-11e9-8eda-6f954aba846b.png)

**Comment by obelyaev** [comment]
Duplicate of #42

**Comment by obelyaev** [comment]
Сделал возможность включать выбирать атрибут dialect внутри cit.
