### ISSUE TITLE
что-то странное в группе леммы

### ISSUE THREAD

**Issue by jvsntsn** [abaevdict/abaevdict#38]
![image](https://user-images.githubusercontent.com/48504970/59496885-0e26a700-8e9b-11e9-8128-65a7354124f8.png)
Не понимаю, к чему отнести вот это вот нежирное курсивное после двоеточия -- это же явно не причастие, а пре-, посткомменты можно оставлять только к lemmaVariant, чего тут тоже нет...

**Comment by obelyaev** [comment]
Это же просто Subentry (PreSubentryGroup)! Если нет Sense, перед ним автоматически ставится двоеточие.

**Comment by obelyaev** [comment]
Изменил вход так, что теперь отображается правильно.
