### ISSUE TITLE
неразборчивая буква

### ISSUE THREAD

**Issue by jvsntsn** [abaevdict/abaevdict#39]
Не могу разобрать, что за буква идет в слове, начинающемся с faer... после r
![image](https://user-images.githubusercontent.com/48504970/59548682-78068580-8f5b-11e9-9ce8-3bbbee574b2e.png)

**Comment by obelyaev** [comment]
Я думаю, это færīsʒæn

**Comment by obelyaev** [comment]
Это слово ængʷylʒ? Я не вижу его в словаре, так что не могу исправить.

**Comment by jvsntsn** [comment]
Спасибо! Да, я еще не вносила его именно в базу, теперь внесу все сразу как надо.

**Comment by jvsntsn** [comment]
еще одна неразборчивая буква, слово aertxuron
![image](https://user-images.githubusercontent.com/48504970/64904536-1bd70d00-d6d4-11e9-9071-c0fb6547e16c.png)

**Comment by obelyaev** [comment]
Простите, не вижу, где тут неразборчивая буква. Или мы это уже обсуждали и поняли, в чём дело?

**Comment by jvsntsn** [comment]
Я тоже сейчас не вижу, давайте тогда это закроем.

**Comment by obelyaev** [comment]
Закрываю. Вообще же предлагаю всё-таки не создавать мега-issues, а для каждого вопроса делать отдельный. Дело в том, что иначе трудно уследить, какие "подвопросы" уже разрешены, а какие нет.
