### ISSUE TITLE
Одинаковые входы

### ISSUE THREAD

**Issue by DariaZhornik** [abaevdict/abaevdict#4]
Что делать, если у двух слов (заголовков словарных статей) одинаковый иронский облик? Нельзя ведь завести две статьи с одинаковыи названиями в ТЛехе. В самом словаре в этом случае перед вторым словом ставится верхний индекс 2.

**Comment by solanum-tuberosum** [comment]
Да, у меня тоже такое встретилось, но, видимо, мы оставляем так, как и делает Тлех?

**Comment by obelyaev** [comment]
Мы решили сделать HomonymNumber полем, заполняемым вручную. Тогда туда просто вносится тот же номер, что у Абаева.

**Comment by obelyaev** [comment]
Сделал новый атрибут HomonymNumber, заполняемый целым числом (Integer) вручную.
