### ISSUE TITLE
Необходимость вставить нечто между "д." и собственно формой

### ISSUE THREAD

**Issue by DariaZhornik** [abaevdict/abaevdict#40]
ʒyrǧa | ʒirǧæg ‛часть плуга (резец или нож)’; д. мн. ч. ʒirǧægutæ ‛плужные резцы’

ʒirǧægutæ -- SubEntry, д. -- Type. Как я понимаю, на данный момент никакой возможности вставить что-либо между ними нет, что же делать с несчастным "мн.ч."?

**Comment by obelyaev** [comment]
Жуть. Подумаю, как это сделать. Очередные прекомменты плодить не хочется, но не очень понятно, что тут ещё можно сделать…

**Comment by obelyaev** [comment]
Добавил атрибут Gram с выбором из списка, что ж делать…
