### ISSUE TITLE
Ссылка на литературу у Subentry

### ISSUE THREAD

**Issue by DariaZhornik** [abaevdict/abaevdict#41]
ʒyrǧa | ʒirǧæg ‛часть плуга (резец или нож)’; д. мн. ч. ʒirǧægutæ ‛плужные резцы’ (SD 2453). 

Насколько я понимаю, на данный момент возможности добавить сноску к SubEntry нет? Что делать?

**Comment by obelyaev** [comment]
Наверное, надо всё-таки предусмотреть такую возможность.

**Comment by obelyaev** [comment]
Добавил возможность вставлять элемент Source внутрь Subentry.
