### ISSUE TITLE
Диалект в скобочках у языка

### ISSUE THREAD

**Issue by DariaZhornik** [abaevdict/abaevdict#42]
груз. (рачин.) mč’lak’vi ‛кушанье из лука’

Пока писала это всё обычным текстом, а не cit'ом.
Как вставить диалект в скобочках к языку?

**Comment by jvsntsn** [comment]
Кстати в скобочках может быть не только диалект...
![image](https://user-images.githubusercontent.com/48504970/59763828-17e94980-92a3-11e9-96da-a673c353f8ff.png)

**Comment by obelyaev** [comment]
Наверное, всё-таки сделаю одно поле для "комментария в скобках" — можно условно назвать его Dialect и писать туда всё подряд.

**Comment by obelyaev** [comment]
> Кстати в скобочках может быть не только диалект...
> ![image](https://user-images.githubusercontent.com/48504970/59763828-17e94980-92a3-11e9-96da-a673c353f8ff.png)

Я в итоге всё-таки сделал диалекты закрытым списком, а не свободным полем, так как счёл более важным единообразный перевод названий разных диалектов (иначе у всех могут быть разные идеи о том, как переводить какой-нибудь рачинский, например). Вообще говоря, не очень понятно, что ухудшится в этом примере, если поставить "(из пехл.)" не до, а после армянского слова и его перевода: "арм. anušak `вечный' (из пехл.)". Заводить отдельное поле "источник слова" ради таких случаев как-то не хочется. Поэтому я предлагаю пока что сделать так, как я написал, а потом посмотреть, насколько часто это встречается.

**Comment by obelyaev** [comment]
Я так понимаю, что слово ænus пока не введено. Когда будете вводить, напишите, пожалуйста, в notes про эту проблему, чтобы не забыть (я завёл такое поле специально для разных комментариев).

**Comment by solanum-tuberosum** [comment]
А у меня в слове iʒægnæ встретилось в скобочках диал.
![image](https://user-images.githubusercontent.com/13102259/61358705-9a096580-a883-11e9-9253-402689141e5f.png)
Я просто написала (диал.) в PreComment к form у Cit. Это правильно?

**Comment by solanum-tuberosum** [comment]
Слово kard, встретились еще такие пометы в скобочках (пока все записала в PreComment к Cit)
![image](https://user-images.githubusercontent.com/13102259/61617271-06fd7080-ac73-11e9-9e02-9bb164630ad8.png)

**Comment by solanum-tuberosum** [comment]
Слово kakon, встретилось еще вот такое:
тюрк. жирненькое, а потом три элемента нежирненькие и без скобок
![image](https://user-images.githubusercontent.com/13102259/62875298-783cba80-bd2b-11e9-821d-b4a9f8b69c9f.png)

PS еще в списке литературы нет Vambery

**Comment by solanum-tuberosum** [comment]
Еще встретилось вот такое, слово iw 'один'.
![image](https://user-images.githubusercontent.com/13102259/64918742-3def8e80-d7ab-11e9-993e-60a578fa42d4.png)
Запихнула это в прекоммент, так и надо делать? или просто добавить в "диалект" еще пометы "диал." и "литер" для удобства?

**Comment by solanum-tuberosum** [comment]
Слово kark, снова встретилось диал.
![image](https://user-images.githubusercontent.com/13102259/65897597-4f928200-e3b8-11e9-88dc-4a080c984fec.png)
Хотелось бы иметь возможность его просто выбирать из списка, наверно

**Comment by obelyaev** [comment]
Добавить эти штуки в список диалектов.

**Comment by solanum-tuberosum** [comment]
Еще они есть в слове kaw
![image](https://user-images.githubusercontent.com/13102259/66124185-6b7e6980-e5ec-11e9-95e0-b719258357a8.png)

**Comment by solanum-tuberosum** [comment]
Слово kæd. Тут скобочки отделены от языка. Продублировать язык?
![image](https://user-images.githubusercontent.com/13102259/66148771-55879d80-e61a-11e9-8cd4-f37696c455b9.png)

**Comment by solanum-tuberosum** [comment]
Еще здесь диал.
![image](https://user-images.githubusercontent.com/13102259/66291841-763a4680-e8eb-11e9-9358-a8453ab40ab8.png)

**Comment by solanum-tuberosum** [comment]
Набрела на слово kaert 'двор'
Тут гора этих штук
![image](https://user-images.githubusercontent.com/13102259/66925198-a8a71a80-f034-11e9-9d74-ef07d6aa2a00.png)
(Плюс еще явно нет одного источника)

**Comment by solanum-tuberosum** [comment]
![image](https://user-images.githubusercontent.com/13102259/66926646-16ecdc80-f037-11e9-9636-d58dbdde5a29.png)

**Comment by solanum-tuberosum** [comment]
![image](https://user-images.githubusercontent.com/13102259/66927699-eefe7880-f038-11e9-8b0d-d48a79983972.png)

**Comment by solanum-tuberosum** [comment]
![image](https://user-images.githubusercontent.com/13102259/67748510-26f3bb80-fa3c-11e9-88d7-a2109a1df941.png)
здесь тоже

**Comment by obelyaev** [comment]
> Слово kakon, встретилось еще вот такое:
> тюрк. жирненькое, а потом три элемента нежирненькие и без скобок
> ![image](https://user-images.githubusercontent.com/13102259/62875298-783cba80-bd2b-11e9-821d-b4a9f8b69c9f.png)
> 
> PS еще в списке литературы нет Vambery

Эти тюркские даны в списке как отдельные языки, поэтому они и не в скобках. Сделал как отдельные cit'ы. В первом случае отметил "тюрк." и "джагат.". В остальных случаях, где в скобках, добавил в список диалектов.
