### ISSUE TITLE
Несколько ссылок на литературу в языковых примерах

### ISSUE THREAD

**Issue by jvsntsn** [abaevdict/abaevdict#43]
Мы умеем ссылаться на несколько источников примера?..
![image](https://user-images.githubusercontent.com/48504970/59761489-a78bf980-929d-11e9-8213-3bebc2218721.png)

**Comment by obelyaev** [comment]
не умеем, но я это сделаю :)

**Comment by obelyaev** [comment]
Добавил возможность сделать несколько Source'ов, но слова этого вроде нет пока в базе, так что не добавил.
