### ISSUE TITLE
Два перевода в примере

### ISSUE THREAD

**Issue by jvsntsn** [abaevdict/abaevdict#44]
Кажется, это что-то вроде MidSubentry, затесавшийся в примерах, если это уже всплывало, извините, я сначала приняла это за два перевода примера, испугалась и побежала делать issue))
![image](https://user-images.githubusercontent.com/48504970/59939262-0e591080-9460-11e9-90c4-bcf1620f129e.png)

**Comment by obelyaev** [comment]
Тут вообще сложный случай, потому что тут получается, что пример находится внутри Subentry, иллюстрируя именно это выражение (обратите внимание на двоеточие). Можно, конечно, предусмотреть Example внутри SubentryGroup…

**Comment by obelyaev** [comment]
Сделал это, см. слово æræǵy
