### ISSUE TITLE
PostComment к Example

### ISSUE THREAD

**Issue by solanum-tuberosum** [abaevdict/abaevdict#45]
Встретилось вот такое
![image](https://user-images.githubusercontent.com/13102259/61359013-37fd3000-a884-11e9-8d12-7ffd4b215f27.png)
Попробовала написать PostComment к Example, но все показывается в неправильном порядке:
![image](https://user-images.githubusercontent.com/13102259/61358960-1ac86180-a884-11e9-9336-6cc4138b4bf5.png)
Что делать?

**Comment by obelyaev** [comment]
Сделать это как PostSubentryGroup с PreComment и ExampleGroup (тогда появится двоеточие).

**Comment by obelyaev** [comment]
cf. #74

**Comment by obelyaev** [comment]
Надо подумать, что здесь делать с точкой тире.

**Comment by obelyaev** [comment]
Может быть, надо добавить возможность вручную заменять знак препинания.

**Comment by solanum-tuberosum** [comment]
Тут какая-то жесть
![image](https://user-images.githubusercontent.com/13102259/67756308-cc159080-fa4a-11e9-9614-a21d6f3c236b.png)
![image](https://user-images.githubusercontent.com/13102259/67756323-d3d53500-fa4a-11e9-9f90-2fcc30097f24.png)
похоже на какой-нибудь PostComment (со слов "В начале июля"), но после него ссылка на лит-ру. И дальше продолжают идти примеры... Но после точки, а не точки с запятой, т.е. нельзя оформить эту огромную штуку как пример без примера... Или забить и оформить именно так?

**Comment by jvsntsn** [comment]
> Тут какая-то жесть
> ![image](https://user-images.githubusercontent.com/13102259/67756308-cc159080-fa4a-11e9-9614-a21d6f3c236b.png)
> ![image](https://user-images.githubusercontent.com/13102259/67756323-d3d53500-fa4a-11e9-9f90-2fcc30097f24.png)
> похоже на какой-нибудь PostComment (со слов "В начале июля"), но после него ссылка на лит-ру. И дальше продолжают идти примеры... Но после точки, а не точки с запятой, т.е. нельзя оформить эту огромную штуку как пример без примера... Или забить и оформить именно так?

Мб это посткоммент к постсабэнтри?) Как цитата из чувака. К сабэнтри по идее можно сделать свои примеры, но перед ними будет двоеточие, а не точка.

**Comment by solanum-tuberosum** [comment]
@jvsntsn 
А вот здесь (слово kæsyn)
![image](https://user-images.githubusercontent.com/13102259/67843257-af419180-fb0c-11e9-8585-a6197093ef8c.png)
Сначала постсабэнтригруп с прекомментом и с посткомментом к Sense, видимо (где ссылка на литру). Потом еще две постсабэнтригруп.
А потом еще одна постсабэнтригруп - но снова с прекомментом (границы выделена желтым). Но перед прекомментом не ставится точка и тире, там точка с запятой. Но это явно постсабэнтригруп, потому что к ней потом идут примеры через двоеточие

**Comment by solanum-tuberosum** [comment]
А вот еще посткоммент к примеру
![image](https://user-images.githubusercontent.com/13102259/67854088-be323f00-fb20-11e9-858b-06cd69442d8d.png)

**Comment by solanum-tuberosum** [comment]
Вот еще посткоммент странный, я пока его не писала никуда (видимо, это будет посткоммент к лемме? Или что?)
![image](https://user-images.githubusercontent.com/13102259/68017693-4db62a00-fca8-11e9-97aa-901381d4bb69.png)

**Comment by obelyaev** [comment]
> > Тут какая-то жесть
> > ![image](https://user-images.githubusercontent.com/13102259/67756308-cc159080-fa4a-11e9-9614-a21d6f3c236b.png)
> > ![image](https://user-images.githubusercontent.com/13102259/67756323-d3d53500-fa4a-11e9-9f90-2fcc30097f24.png)
> > похоже на какой-нибудь PostComment (со слов "В начале июля"), но после него ссылка на лит-ру. И дальше продолжают идти примеры... Но после точки, а не точки с запятой, т.е. нельзя оформить эту огромную штуку как пример без примера... Или забить и оформить именно так?
> 
> Мб это посткоммент к постсабэнтри?) Как цитата из чувака. К сабэнтри по идее можно сделать свои примеры, но перед ними будет двоеточие, а не точка.

Вроде бы, так и есть, и вы это реализовали.

**Comment by obelyaev** [comment]
> @jvsntsn
> А вот здесь (слово kæsyn)
> ![image](https://user-images.githubusercontent.com/13102259/67843257-af419180-fb0c-11e9-8585-a6197093ef8c.png)
> Сначала постсабэнтригруп с прекомментом и с посткомментом к Sense, видимо (где ссылка на литру). Потом еще две постсабэнтригруп.
> А потом еще одна постсабэнтригруп - но снова с прекомментом (границы выделена желтым). Но перед прекомментом не ставится точка и тире, там точка с запятой. Но это явно постсабэнтригруп, потому что к ней потом идут примеры через двоеточие

По смыслу это именно PostSubentryGroup с прекомментом. Почему же там точка и тире? Либо потому, что для Абаева очень важно выделить этот послелог (в принципе действительно синхронно это не просто идиома, а самостоятельная лексема из-за изменения начальной согласной), либо потому, что уже следует за блоком примеров. Но вообще даже в постпозиции к примерам в других местах Subentry друг от друга отделяются именно точками с запятой, верно? (просто я уже не помню) Если так, то предлагаю здесь оставить как есть, т.е. точку с запятой.

**Comment by obelyaev** [comment]
> Вот еще посткоммент странный, я пока его не писала никуда (видимо, это будет посткоммент к лемме? Или что?)
> ![image](https://user-images.githubusercontent.com/13102259/68017693-4db62a00-fca8-11e9-97aa-901381d4bb69.png)

Посткоммент к лемме у нас кагбе не бывает, но по смыслу это именно оно. После блока примеров у нас могут следовать только ещё примеры или сабэнтри. Это — ни то, ни другое, а некая цитата, иллюстрирующая значение слова. Тогда сделаю так, чтобы у Lemma был посткоммент до этимологии.
