### ISSUE TITLE
ссылка на Миллера

### ISSUE THREAD

**Issue by solanum-tuberosum** [abaevdict/abaevdict#46]
Встретилось вот такое
![image](https://user-images.githubusercontent.com/13102259/61369145-2aea3c00-a898-11e9-8305-825fb64f0151.png)
Видимо, имеется в виду Вс. Миллер. ОЭ 260 и Вс. Миллер. Сл. II 651-652, но Миллер второй раз опущен (на самом деле такое часто встречается, но я только что поняла, что Сл относится тоже к Миллеру).
Надо делать не как у Абаева и два раза повторять? Я пока просто Сл. записала текстом

**Comment by solanum-tuberosum** [comment]
И в этом же слове нет ссылки на литературу
![image](https://user-images.githubusercontent.com/13102259/61369625-2b370700-a899-11e9-8c06-cef61593c3cc.png)

**Comment by solanum-tuberosum** [comment]
> Встретилось вот такое
> ![image](https://user-images.githubusercontent.com/13102259/61369145-2aea3c00-a898-11e9-8305-825fb64f0151.png)
> Видимо, имеется в виду Вс. Миллер. ОЭ 260 и Вс. Миллер. Сл. II 651-652, но Миллер второй раз опущен (на самом деле такое часто встречается, но я только что поняла, что Сл относится тоже к Миллеру).
> Надо делать не как у Абаева и два раза повторять? Я пока просто Сл. записала текстом

Хотя эта гипотеза с Миллером не подтверждается вот этим
![image](https://user-images.githubusercontent.com/13102259/61370436-13608280-a89b-11e9-9ebc-4cfba5dcd4ef.png)
Так что видимо надо просто добавить СЛ?

**Comment by solanum-tuberosum** [comment]
C этим миллером одни проблемы. В слове īnnæ вот такая ссылка. Это все один Миллер ОЭ, а остальное ему в текстовое поле писать?
![image](https://user-images.githubusercontent.com/13102259/61435822-11053380-a942-11e9-9fe1-7615c2e1c3e9.png)

**Comment by solanum-tuberosum** [comment]
Слово _ir_, нет источника "Акты Кавк. археограф. комиссии"
![image](https://user-images.githubusercontent.com/13102259/61443637-92fd5880-a952-11e9-98c5-e006ef734bc9.png)

**Comment by solanum-tuberosum** [comment]
Слово jæw, нет источника Н. Анфимов...
![image](https://user-images.githubusercontent.com/13102259/61542852-05e9fa80-aa4b-11e9-9d43-40786b3cd6d4.png)

**Comment by solanum-tuberosum** [comment]
Еще нет источника
![image](https://user-images.githubusercontent.com/13102259/61544479-3c754480-aa4e-11e9-94dc-383f0c09067e.png)

**Comment by jvsntsn** [comment]
Еще нет Марка в компании евангелистов)
![image](https://user-images.githubusercontent.com/48504970/61550521-55d0bd80-aa5b-11e9-9ff4-7b40c7cc9191.png)

**Comment by solanum-tuberosum** [comment]
снова нет Сл., очень грустно без него жить, оно везде
![image](https://user-images.githubusercontent.com/13102259/61577246-66317880-aaed-11e9-81ee-b017c2568e95.png)

**Comment by solanum-tuberosum** [comment]
> снова нет Сл., очень грустно без него жить, оно везде
> ![image](https://user-images.githubusercontent.com/13102259/61577246-66317880-aaed-11e9-81ee-b017c2568e95.png)

UPD я нашла Сл. в списке осетинских источников (к примерам), но он используется не только с ними, как показано выше

**Comment by solanum-tuberosum** [comment]
Слово kaʒī, вот еще две ссылки на литературу, которых нет:
![image](https://user-images.githubusercontent.com/13102259/61613627-833f8600-ac6a-11e9-9194-0f6d27d9446a.png)

**Comment by solanum-tuberosum** [comment]
Слово kadæg
![image](https://user-images.githubusercontent.com/13102259/61613668-9eaa9100-ac6a-11e9-8aec-2e4f26ef42ac.png)
Продолжаются проблемы с Миллером. Мб сделать так, что Ws Miller записывалось бы в поле "автор"? чтобы мочь его убрать при необходимости.

**Comment by solanum-tuberosum** [comment]
Слово kard, есть Munkacsi, но нет KSz
![image](https://user-images.githubusercontent.com/13102259/61617105-b6861300-ac72-11e9-9dc5-8306a69f0d59.png)

**Comment by solanum-tuberosum** [comment]
Снова этот Миллер и его Gr.
Еще я не помню, как ссылаться на осетинские источники в PostComment к Sense -- там вот Коста нужен просто.
![image](https://user-images.githubusercontent.com/13102259/61629587-01f9ea80-ac8e-11e9-9bba-0fb745dea37a.png)

**Comment by solanum-tuberosum** [comment]
Слово kalyn и Миллер
![image](https://user-images.githubusercontent.com/13102259/61632476-9a479d80-ac95-11e9-8ff4-072e1655eabf.png)

**Comment by solanum-tuberosum** [comment]
Слово kajyn
Нет источника Uhlenbeck
![image](https://user-images.githubusercontent.com/13102259/62831314-ae901200-bc25-11e9-91e7-0cfa20b4af6d.png)

**Comment by solanum-tuberosum** [comment]
У нас в источниках есть только ОЯФ I, но мне встретился просто ОЯФ
![image](https://user-images.githubusercontent.com/13102259/62880074-42043880-bd35-11e9-985c-a69d74e0e68d.png)

**Comment by solanum-tuberosum** [comment]
Снова Миллер..... Слово īrvæzyn
![image](https://user-images.githubusercontent.com/13102259/64527880-c683b000-d30f-11e9-975d-d7cc69e1bb46.png)

**Comment by solanum-tuberosum** [comment]
![image](https://user-images.githubusercontent.com/13102259/64533627-8f67cb80-d31c-11e9-8d61-63b95f8bf25c.png)
не могу выбрать этот источник, видимо, он в другом списке?

**Comment by solanum-tuberosum** [comment]
Слово īx | ех
Нет источника:
![image](https://user-images.githubusercontent.com/13102259/64877818-d1657a00-d65a-11e9-9eb3-b19c53dc8bda.png)

**Comment by solanum-tuberosum** [comment]
Снова Сл... пока запихнула в Миллера
![image](https://user-images.githubusercontent.com/13102259/64904054-a7e53680-d6cc-11e9-9428-2fa9ee31562f.png)

**Comment by jvsntsn** [comment]
еще нужно добавить Марка к компании евангелистов (слово aergom)
![image](https://user-images.githubusercontent.com/48504970/64904588-c0f1e580-d6d4-11e9-9eec-9de493738877.png)

**Comment by jvsntsn** [comment]
вот этого нет в источниках, слово ævdaʒy
[image](https://user-images.githubusercontent.com/48504970/65893874-6c778700-e3b1-11e9-903a-1c276e9206e8.png)

**Comment by solanum-tuberosum** [comment]
Слово kark, не нашла Гесихия
![image](https://user-images.githubusercontent.com/13102259/65897694-8799c500-e3b8-11e9-83a0-91a1b3f9f238.png)

**Comment by obelyaev** [comment]
> Снова этот Миллер и его Gr.
> Еще я не помню, как ссылаться на осетинские источники в PostComment к Sense -- там вот Коста нужен просто.
> ![image](https://user-images.githubusercontent.com/13102259/61629587-01f9ea80-ac8e-11e9-9bba-0fb745dea37a.png)

Добавить Source как элемент Text_RU/Text_EN

**Comment by solanum-tuberosum** [comment]
Вот еще нет в списке литературы (+здесь еще тоже надо прятать язык)
![image](https://user-images.githubusercontent.com/13102259/66251785-7c4ded00-e75c-11e9-919f-ce3b7ac3361e.png)

**Comment by solanum-tuberosum** [comment]
Нет еще двух источников
![image](https://user-images.githubusercontent.com/13102259/66904818-6c13f880-f00d-11e9-86b6-aafd5eb30acd.png)

**Comment by solanum-tuberosum** [comment]
Еще вот ребят нет
![image](https://user-images.githubusercontent.com/13102259/66910444-3ecc4800-f017-11e9-91a5-d2b69107c3ff.png)

**Comment by jvsntsn** [comment]
еще вот такого нет 
![image](https://user-images.githubusercontent.com/48504970/66921095-32eb8080-f02d-11e9-9d21-72f3d8161559.png)

слово ævgæny

**Comment by solanum-tuberosum** [comment]
Слово kaenyn
1. Здесь тоже Миллер
2. Автор опускается и у PSt тоже!
3. Tedesko можно тоже записать в авторов. Вообще много где можно записать авторов, если будет возможность их опускать
![image](https://user-images.githubusercontent.com/13102259/66922360-94acea00-f02f-11e9-9308-291cc8884b0d.png)

**Comment by solanum-tuberosum** [comment]
Слово kæræf
![image](https://user-images.githubusercontent.com/13102259/67026607-cfd31a00-f110-11e9-9113-45674be2c7fb.png)
A 621 должно быть в поле Text? В списке есть просто "Gershevitch".
Тут же еще нет такой ссылки:
![image](https://user-images.githubusercontent.com/13102259/67026689-fdb85e80-f110-11e9-99e4-738000ec867f.png)

**Comment by solanum-tuberosum** [comment]
Слово kaerc
![image](https://user-images.githubusercontent.com/13102259/67089526-84704880-f1b0-11e9-9dab-a196211630ef.png)

**Comment by solanum-tuberosum** [comment]
Слово kærʒyn
![image](https://user-images.githubusercontent.com/13102259/67224238-69643980-f439-11e9-84c9-58456e7a5437.png)

**Comment by solanum-tuberosum** [comment]
Слово kærī
![image](https://user-images.githubusercontent.com/13102259/67317984-8836fe80-f513-11e9-8e55-7a99b86aa7c1.png)

**Comment by jvsntsn** [comment]
слово ævz-
![image](https://user-images.githubusercontent.com/48504970/67497855-429b4280-f687-11e9-917c-cf21218765b4.png)
Одного IIFL нет, но есть Morgenstierne. IIFL, на которого Абаев сослался двумя строчками выше, но имеется ли в виду этот же Morgenstierne?...
в последнем ref'e в списке есть просто MSL, но все равно не понятно, что делать со всем тем, что между автором и этим MSL

**Comment by solanum-tuberosum** [comment]
Слово kæsag. здесь тоже надо спрятать автора (т.к. у нас идет одним "Bailey. Asica")
![image](https://user-images.githubusercontent.com/13102259/67748577-4854a780-fa3c-11e9-86f9-b615877b6fd6.png)
еще нет источника (в сноске)
![image](https://user-images.githubusercontent.com/13102259/67748596-530f3c80-fa3c-11e9-81d5-a3619c28f2a8.png)

**Comment by solanum-tuberosum** [comment]
Слово kæxc
![image](https://user-images.githubusercontent.com/13102259/68016919-9d93f180-fca6-11e9-921f-aa57c27c2147.png)

**Comment by solanum-tuberosum** [comment]
Слово keǧog
![image](https://user-images.githubusercontent.com/13102259/68017722-63c3ea80-fca8-11e9-8909-a86aef766997.png)

**Comment by obelyaev** [comment]
Из списка литературы у Абаева очевидно, что "Сл." в осетинских источниках и словарь Миллера в списке источников неосетинских — это одно и то же. Поэтому не нужно ничего никуда добавлять, а просто там, где "Сл." не в примерах, ссылаться на Миллера. Другой вопрос — что делать с повторением имени автора. Писать всё в поле текст неправильно, т.к. теряется смысл в поддержании такого каталога переводов. Но и реализовать полноценную систему цитирований с учётом автора и т.д. мы тоже не можем. Пока, думаю, пусть повторяется. В электронной версии это не беда, а в бумажной можно, в конце концов, как-то убрать при финальной редактуре.
