### ISSUE TITLE
source в cit

### ISSUE THREAD

**Issue by solanum-tuberosum** [abaevdict/abaevdict#47]
Слово _imonaw_
![image](https://user-images.githubusercontent.com/13102259/61430095-7c92d500-a931-11e9-90df-48c4d71a8262.png)
Мне нужно было поставить ссылку внутри cit. Я нашла, что можно добавить source, но 1. такого источника в списке нет; 2. он показывается не в том порядке потом (вставила для примера другой источник):
![image](https://user-images.githubusercontent.com/13102259/61430069-66851480-a931-11e9-88bd-4cb36bd30dc7.png)

**Comment by obelyaev** [comment]
1. Сделать возможность добавлять ref в form.

2. Разобраться с порядком следования элементов.

**Comment by obelyaev** [comment]
Исправил.
