### ISSUE TITLE
нет языка

### ISSUE THREAD

**Issue by solanum-tuberosum** [abaevdict/abaevdict#48]
Слово _īnnæ_
Нет пали:
![image](https://user-images.githubusercontent.com/13102259/61435537-5b39e500-a941-11e9-95a5-c7fc0b6c43f7.png)

**Comment by solanum-tuberosum** [comment]
слово ird
не нашла пашан
![image](https://user-images.githubusercontent.com/13102259/61577144-be677b00-aaeb-11e9-8992-7ea064aa2250.png)

**Comment by solanum-tuberosum** [comment]
Слово kard, нет хантыйского
![image](https://user-images.githubusercontent.com/13102259/61617195-e208fd80-ac72-11e9-94e0-1aa70b0c3623.png)

**Comment by solanum-tuberosum** [comment]
Слово kalyn, нет тохар. B (только просто тохар.)
![image](https://user-images.githubusercontent.com/13102259/61632535-c400c480-ac95-11e9-8b17-14bcb39f78c9.png)

**Comment by solanum-tuberosum** [comment]
мазаид.
![image](https://user-images.githubusercontent.com/13102259/62880020-1da85c00-bd35-11e9-8b03-781fe7d07504.png)
+ NB ст.слав с большой буквы

**Comment by solanum-tuberosum** [comment]
заза
![image](https://user-images.githubusercontent.com/13102259/64869221-9dce2400-d649-11e9-89be-eb93020d7b8e.png)

**Comment by jvsntsn** [comment]
нет языка кар., в слове aerx
![image](https://user-images.githubusercontent.com/48504970/64890825-21533980-d679-11e9-81c4-1e840a02d791.png)
и еще нет языка заза, встретившегося в слове ærqīs

**Comment by jvsntsn** [comment]
нет языка вершик. (но есть верш. -- это одно и то же?)
![image](https://user-images.githubusercontent.com/48504970/64918400-62953780-d7a6-11e9-9baa-f703f71d350e.png)

**Comment by jvsntsn** [comment]
еще заза в слове aestaj

![image](https://user-images.githubusercontent.com/48504970/64922409-95a3ef00-d7d7-11e9-945e-4b122b22ef40.png)

**Comment by solanum-tuberosum** [comment]
Слово kark, не нашла пам. н. (?)
![image](https://user-images.githubusercontent.com/13102259/65897655-6df87d80-e3b8-11e9-9462-7d402ac50e59.png)

**Comment by solanum-tuberosum** [comment]
Слово kaem, снова заза
![image](https://user-images.githubusercontent.com/13102259/66761946-acf4fb80-eead-11e9-9dc8-72eb3b8d1fe1.png)

**Comment by jvsntsn** [comment]
нет гур.
![image](https://user-images.githubusercontent.com/48504970/66944857-ac4b9900-f056-11e9-9830-4529d644a235.png)
слово ævgærdæn

**Comment by jvsntsn** [comment]
![image](https://user-images.githubusercontent.com/48504970/67235692-45602280-f450-11e9-9e5a-ae98551e33d7.png)
слово ævnalyn

**Comment by solanum-tuberosum** [comment]
Слово kæsyn
![image](https://user-images.githubusercontent.com/13102259/67843523-3131ba80-fb0d-11e9-953a-1afe413b2ef5.png)
и здесь еще #42

**Comment by obelyaev** [comment]
Всё добавил. Кое-где непонятно, что Абаев имел в виду (или это опечатки?), там поставил вопросики. Потом разберусь по ссылкам.
