### ISSUE TITLE
subentry и postcomment

### ISSUE THREAD

**Issue by solanum-tuberosum** [abaevdict/abaevdict#49]
![image](https://user-images.githubusercontent.com/13102259/61436391-59712100-a943-11e9-86f1-ff55389f1fba.png)
Я внесла īnnæbon ‛послезавтра’ в subentry
но тогда "буквально „в другой день“;" должно идти как посткоммент. Надо тогда добавить еще запятую как вид разделителя?

**Comment by obelyaev** [comment]
Добавить запятую как вид разделителя посткоммента.

**Comment by obelyaev** [comment]
Добавил.
