### ISSUE TITLE
перекрестные ссылки на статьи в этимологии

### ISSUE THREAD

**Issue by jvsntsn** [abaevdict/abaevdict#5]
У меня в этимологии встретилась вот такая штука (на скрине). Кажется, тлех не умеет делать ссылки из этимологии в одну статью два раза (если я правильно поняла). Как быть в таком случае?
![image](https://user-images.githubusercontent.com/48504970/55015640-4934df00-4ffe-11e9-938f-b0135051958c.png)

**Comment by obelyaev** [comment]
В этом случае надо ссылаться на первое слово (т.е., как правило, иронскую форму — Headword). Далее вертикальная черта и дигорская форма пишутся простым текстом, т.е. <ref>æncajyn</ref> | %iæncajun%i .
