### ISSUE TITLE
Нестандартные источники у примеров или PostComment к Example

### ISSUE THREAD

**Issue by solanum-tuberosum** [abaevdict/abaevdict#52]
![image](https://user-images.githubusercontent.com/13102259/61461104-b6d39500-a978-11e9-8455-47c6934041a2.png)
записала "из слов..." в PostComment, но он показывается до переводов:
![image](https://user-images.githubusercontent.com/13102259/61461154-cce15580-a978-11e9-9f5b-935b4d53ad9f.png)

**Comment by obelyaev** [comment]
Поискать случаи, когда PostComment к Example — есть ли настоящие случаи, где он должен быть между примером и переводом?

**Comment by solanum-tuberosum** [comment]
Вот еще
![image](https://user-images.githubusercontent.com/13102259/67141910-1ccb0380-f26b-11e9-98e9-54f40194f646.png)

**Comment by solanum-tuberosum** [comment]
![image](https://user-images.githubusercontent.com/13102259/67471242-c0475a00-f657-11e9-9c69-c2db13a06637.png)

**Comment by obelyaev** [comment]
Дело в таких случаях поле Abbrev пустым, а текст писать в поле Text. Нет смысла всё это вбивать в очередной список (в отличие от диалектов, где перевод неочевиден и должен быть последователен).

Аналогично я делаю для отсутствующих источников (а пунктуацию и пробелы потом можно поправить скриптом).
