### ISSUE TITLE
вариант слова + перевод

### ISSUE THREAD

**Issue by solanum-tuberosum** [abaevdict/abaevdict#53]
![image](https://user-images.githubusercontent.com/13102259/61462498-6447a800-a97b-11e9-974c-2926f97db6f3.png)
я уже не помню, честно говоря, что мы решили делать со скобочками.
если я делаю LemmaVariant, то оно пойдет через запятую
неужели писать в PreComment к Sense?

и проблема с переводом -- в русском здесь _плясать_ и _танцевать_, но если переводить на английский, то получится _dance_ и _dance_...

**Comment by obelyaev** [comment]
Имеет смысл сделать так, чтобы пустой перевод Sense в английском не отображался.

**Comment by obelyaev** [comment]
Сделал так, что пустой перевод исчезает, причём и в русском, и в английском, т.е. в принципе можно иметь и в английском на один перевод больше, если нужно.
