### ISSUE TITLE
склонение названий языков

### ISSUE THREAD

**Issue by solanum-tuberosum** [abaevdict/abaevdict#55]
Скифо-сарматских выделено жирным, как обычные cit на языки, но весьма отличаются от остальных cit
![image](https://user-images.githubusercontent.com/13102259/61539768-e059f280-aa44-11e9-8884-25cc2fe61ed8.png)
Пока написала обычным текстом. Это можно как-нибудь исправить?

**Comment by solanum-tuberosum** [comment]
а здесь двоеточие есть
![image](https://user-images.githubusercontent.com/13102259/64879760-5783bf80-d65f-11e9-89f0-7be186ff0b63.png)

**Comment by solanum-tuberosum** [comment]
![image](https://user-images.githubusercontent.com/13102259/64908284-b5b7ad80-d706-11e9-9d3f-b9f25a6b1425.png)

**Comment by solanum-tuberosum** [comment]
слово kark, коми с большой буквы
![image](https://user-images.githubusercontent.com/13102259/65897723-9e401c00-e3b8-11e9-87dd-e5b1301302ba.png)

**Comment by solanum-tuberosum** [comment]
Слово karz
![image](https://user-images.githubusercontent.com/13102259/65901439-e2cfb580-e3c0-11e9-98ec-b385999ae52a.png)

**Comment by obelyaev** [comment]
Сделать параметр HideLanguage.

**Comment by solanum-tuberosum** [comment]
![image](https://user-images.githubusercontent.com/13102259/66904773-54d50b00-f00d-11e9-8255-4091dd0b7d5a.png)

**Comment by solanum-tuberosum** [comment]
Слово kaenyn
![image](https://user-images.githubusercontent.com/13102259/66922476-d0e04a80-f02f-11e9-9f9c-21c141405971.png)
все еще нет зазы, Перс с большой буквы

**Comment by solanum-tuberosum** [comment]
Слово kæræf
![image](https://user-images.githubusercontent.com/13102259/67026740-10cb2e80-f111-11e9-8252-f35db410aaf4.png)
Видимо, здесь два раза надо спрятать язык, потому что формы разрываются рефом

**Comment by jvsntsn** [comment]
![image](https://user-images.githubusercontent.com/48504970/67387884-66378d80-f5a0-11e9-8639-e4e39d93bb13.png)
ævsymær

**Comment by jvsntsn** [comment]
ævsymær
![image](https://user-images.githubusercontent.com/48504970/67387960-85361f80-f5a0-11e9-826e-6c6db92d6421.png)

**Comment by solanum-tuberosum** [comment]
![image](https://user-images.githubusercontent.com/13102259/67751837-e77c9d80-fa42-11e9-9e04-7d7f3c351929.png)
? что делать

**Comment by solanum-tuberosum** [comment]
Слово kæstaw
![image](https://user-images.githubusercontent.com/13102259/67753487-d1241100-fa45-11e9-8685-be147d8ac836.png)
Между тюркскими словами есть скобочки. Я сделала два цита, во втором надо будет скрыть название языка

**Comment by obelyaev** [comment]
Сделал параметр HideLanguage у cit, если он равен 1, язык и диалект исчезают. Извините, эти примеры не исправлял, т.к. уже времени на это нет. Лишь бы сделать всё, что надо.
