### ISSUE TITLE
Два xrefa в одной статье: форматирование

### ISSUE THREAD

**Issue by solanum-tuberosum** [abaevdict/abaevdict#56]
Нужно сделать так:
![image](https://user-images.githubusercontent.com/13102259/61543398-0d5dd380-aa4c-11e9-8a87-83085b11e4d8.png)
Я делаю два xrefa, но между ними нет запятых:
![image](https://user-images.githubusercontent.com/13102259/61543424-1ea6e000-aa4c-11e9-81d6-76c4981c7e7b.png)

**Comment by obelyaev** [comment]
Уже пофиксили (надо один xref к двум энтрям).
