### ISSUE TITLE
ū и порядок словарных статей

### ISSUE THREAD

**Issue by jvsntsn** [abaevdict/abaevdict#57]
Слова с ū не очень хотят соблюдать тот порядок, в котором они располагаются у Абаева. Например, три слова, идущие подряд у Абаева, в тлехе оказались разбросанными по разным местам...
![image](https://user-images.githubusercontent.com/48504970/61557399-d0560900-aa6c-11e9-8a06-789fd336e1c6.png)
Также слово ūd оказалось между с и d...
![image](https://user-images.githubusercontent.com/48504970/61557464-fda2b700-aa6c-11e9-9a9c-e1c495370cfc.png)
Не знаю, как так вышло и можно ли что-то с этим сделать, но на всякий случай обращаю внимание на этот странный факт

**Comment by obelyaev** [comment]
Настроить сортировку в настройках словаря.

**Comment by obelyaev** [comment]
Это я исправил. У Абаева краткое и долгое u вообще не различаются с т.зр. сортировки. Так и сделал.
