### ISSUE TITLE
форматирование: два xrefa рядом в этимологии

### ISSUE THREAD

**Issue by solanum-tuberosum** [abaevdict/abaevdict#58]
![image](https://user-images.githubusercontent.com/13102259/61577304-32a31e00-aaee-11e9-9446-5b955d01afb7.png)
Решила сделать ссылки на два слова (iron и fændag), т.к. они оба есть в словаре. Но почему-то перед вторым словом ставится автоматически пробел:
![image](https://user-images.githubusercontent.com/13102259/61577316-77c75000-aaee-11e9-9d92-706686745145.png)
Может быть, его убрать?

**Comment by obelyaev** [comment]
Убрать пробел перед xref в настройках стиля.

**Comment by solanum-tuberosum** [comment]
А перед cit'ом тоже стоит пробел? Его тогда тоже надо бы убрать:
![image](https://user-images.githubusercontent.com/13102259/66251116-190c8c80-e755-11e9-9e4d-df3337865110.png)
(слово kæfoj)

**Comment by solanum-tuberosum** [comment]
PS в том же слове kæfoj не понимаю, как лучше перевести слово ногавица
![image](https://user-images.githubusercontent.com/13102259/66251218-8371fc80-e756-11e9-9e8b-010e3021026c.png)
Нашла только вот такое:
![image](https://user-images.githubusercontent.com/13102259/66251220-8cfb6480-e756-11e9-8ad4-076e55fdcd3a.png)
Перевести как trouser-leg?

**Comment by obelyaev** [comment]
> PS в том же слове kæfoj не понимаю, как лучше перевести слово ногавица
> ![image](https://user-images.githubusercontent.com/13102259/66251218-8371fc80-e756-11e9-9e8b-010e3021026c.png)
> Нашла только вот такое:
> ![image](https://user-images.githubusercontent.com/13102259/66251220-8cfb6480-e756-11e9-8ad4-076e55fdcd3a.png)
> Перевести как trouser-leg?

Это gaiter (гетра, то бишь :) )

**Comment by obelyaev** [comment]
Все проблемы с форматированием вроде исправил.
