### ISSUE TITLE
проблемы с переводом

### ISSUE THREAD

**Issue by solanum-tuberosum** [abaevdict/abaevdict#59]
![image](https://user-images.githubusercontent.com/13102259/62830988-c4e79f00-bc20-11e9-96b3-4d9a65ac3c8c.png)
В русском два слова -- плясать и танцевать. А в английском только dance, насколько я понимаю. Как лучше переводить?

**Comment by solanum-tuberosum** [comment]
Слово kalak, что такое винница? Место где пьют вино? Где делают вино? Где продают вино?
![image](https://user-images.githubusercontent.com/13102259/62877095-ff3f6200-bd2e-11e9-9cb3-a1b0fb7b64c2.png)

Вряд ли вот это: 
![image](https://user-images.githubusercontent.com/13102259/62877112-0b2b2400-bd2f-11e9-9da7-0f9b42a89e0b.png)

**Comment by obelyaev** [comment]
winery
