### ISSUE TITLE
Структура статьи

### ISSUE THREAD

**Issue by solanum-tuberosum** [abaevdict/abaevdict#6]
Сейчас структура статьи выглядит так:

LemmaSign[HomonymNumber] {, LemmaVariant} [: Participle] | DigorForm [New] [Type] ‘Sense’ {; ‘Sense’}. {— ExampleGroup.}.

~ Etymology

Но у меня много раз после Sense, но до ExampleGroup встретились словосочетания/слова на осетинском с переводами (примеры на скрине). Т.е. это и не sense, и не example. Нужно обновить структуру леммы, добавить CollocationGroup?

![image](https://user-images.githubusercontent.com/13102259/55020587-2e676800-5008-11e9-9552-0f850030c83c.png)
![image](https://user-images.githubusercontent.com/13102259/55020619-3cb58400-5008-11e9-8267-570d9ccc61de.png)
![image](https://user-images.githubusercontent.com/13102259/55020637-4939dc80-5008-11e9-944b-20eb765bb348.png)
![image](https://user-images.githubusercontent.com/13102259/55020671-5b1b7f80-5008-11e9-8c20-a94598e27def.png)
![image](https://user-images.githubusercontent.com/13102259/55020691-68386e80-5008-11e9-8b65-2e03fba8b63b.png)

**Comment by jvsntsn** [comment]
На скрине у Иры не увидела, но у меня есть случаи, когда после таких коллокаций после тире идёт объяснение проведённого выражения.

**Comment by jvsntsn** [comment]
А еще у меня появились пометы в скобочках без курсива после примера, но до перевода...
![image](https://user-images.githubusercontent.com/48504970/55330061-ca75f100-5498-11e9-8ff5-863a9d889f86.png)

**Comment by solanum-tuberosum** [comment]
Продолжаю путаться в структуре статьи.

Что мы делаем со следующими случаями:
![image](https://user-images.githubusercontent.com/13102259/55860642-6381c780-5b7d-11e9-82c7-fad7193a5e08.png)
![image](https://user-images.githubusercontent.com/13102259/55860658-71374d00-5b7d-11e9-9c67-a2b7ee2cc8ff.png)

Насколько я понимаю, сейчас мы не можем ставить пометы д. и и. в Sense? (типа д. 'дух лесов')
и эти же д. и и. хочется мочь автоматически расставлять и не в самом Sense, но и в Definition? (что делать с и. _qædox_ или с д. см. _qædgom_?)

**Comment by obelyaev** [comment]
> Продолжаю путаться в структуре статьи.
> 
> Что мы делаем со следующими случаями:
> ![image](https://user-images.githubusercontent.com/13102259/55860642-6381c780-5b7d-11e9-82c7-fad7193a5e08.png)
> ![image](https://user-images.githubusercontent.com/13102259/55860658-71374d00-5b7d-11e9-9c67-a2b7ee2cc8ff.png)
> 
> Насколько я понимаю, сейчас мы не можем ставить пометы д. и и. в Sense? (типа д. 'дух лесов')
> и эти же д. и и. хочется мочь автоматически расставлять и не в самом Sense, но и в Definition? (что делать с и. _qædox_ или с д. см. _qædgom_?)

Для ǧædgin и подобных случаев просто отмечаем лемму как дигорскую и добавляем на верхнем уровне элемент xref, без Sense (см. ǧar).

**Comment by obelyaev** [comment]
> А еще у меня появились пометы в скобочках без курсива после примера, но до перевода...
> ![image](https://user-images.githubusercontent.com/48504970/55330061-ca75f100-5498-11e9-8ff5-863a9d889f86.png)

Добавить в Example новое поле типа ExampleComment.

**Comment by jvsntsn** [comment]
> На скрине у Иры не увидела, но у меня есть случаи, когда после таких коллокаций после тире идёт объяснение проведённого выражения.
![image](https://user-images.githubusercontent.com/48504970/55882767-ba06fa00-5bad-11e9-837e-4c7865f159e1.png)

**Comment by obelyaev** [comment]
> > На скрине у Иры не увидела, но у меня есть случаи, когда после таких коллокаций после тире идёт объяснение проведённого выражения.
> > ![image](https://user-images.githubusercontent.com/48504970/55882767-ba06fa00-5bad-11e9-837e-4c7865f159e1.png)

Сделать эти комментарии в TxAfter к Collocation.

**Comment by obelyaev** [comment]
> Сейчас структура статьи выглядит так:
> 
> LemmaSign[HomonymNumber] {, LemmaVariant} [: Participle] | DigorForm [New] [Type] ‘Sense’ {; ‘Sense’}. {— ExampleGroup.}.
> 
> ~ Etymology
> 
> Но у меня много раз после Sense, но до ExampleGroup встретились словосочетания/слова на осетинском с переводами (примеры на скрине). Т.е. это и не sense, и не example. Нужно обновить структуру леммы, добавить CollocationGroup?
> 
> ![image](https://user-images.githubusercontent.com/13102259/55020587-2e676800-5008-11e9-9552-0f850030c83c.png)
> ![image](https://user-images.githubusercontent.com/13102259/55020619-3cb58400-5008-11e9-8267-570d9ccc61de.png)
> ![image](https://user-images.githubusercontent.com/13102259/55020637-4939dc80-5008-11e9-944b-20eb765bb348.png)
> ![image](https://user-images.githubusercontent.com/13102259/55020671-5b1b7f80-5008-11e9-8c20-a94598e27def.png)
> ![image](https://user-images.githubusercontent.com/13102259/55020691-68386e80-5008-11e9-8b65-2e03fba8b63b.png)

Добавить элемент Collocation со сложной структурой.

**Comment by solanum-tuberosum** [comment]
NB

![image](https://user-images.githubusercontent.com/13102259/55885716-1b7d9780-5bb3-11e9-96f4-b6a16d8baafe.png)

**Comment by solanum-tuberosum** [comment]
NB 2
![image](https://user-images.githubusercontent.com/13102259/55886248-09e8bf80-5bb4-11e9-87d7-28aa484cc737.png)

**Comment by obelyaev** [comment]
Реализованы элементы SubentryGroup, Subentry для того, что мы здесь называли "коллокатами", а также элемент Comment для комментариев разных стилей. Форматирование и пунктуация изменяются динамически либо задаётся выбором из списка. Все обсуждаемые в этом issue примеры реализованы в словаре (скоро загружу новую версию на сервер).
