### ISSUE TITLE
форматирование у PostComment'а

### ISSUE THREAD

**Issue by solanum-tuberosum** [abaevdict/abaevdict#60]
надо бы добавить еще возможность перед посткомментом ставить запятую (1) и просто пробел (2)

(1)
![image](https://user-images.githubusercontent.com/13102259/62876051-cbfbd380-bd2c-11e9-9bbe-732dce422256.png)

(2) то же слово - в посткомменте ссылка на лит-ру
![image](https://user-images.githubusercontent.com/13102259/62876105-e59d1b00-bd2c-11e9-9f0f-f4d95c0bf826.png)

**Comment by solanum-tuberosum** [comment]
здесь тоже нужна запятая в посткомменте
![image](https://user-images.githubusercontent.com/13102259/64868722-90646a00-d648-11e9-9797-e90359fde941.png)

**Comment by solanum-tuberosum** [comment]
![image](https://user-images.githubusercontent.com/13102259/64909651-c45a9080-d717-11e9-9378-879bc466bbeb.png)
слово iw (второе)
решила запихнуть это все в cit, но тогда надо тоже мочь в посткомменте ставить просто пробелы

**Comment by obelyaev** [comment]
Запятую уже обсуждали, а пробел можно сделать вручную. Почему-то в английском появляется точка с запятой, это надо пофиксить. 

Ещё в том же слове в англ. a particle не отделяется от LemmaSign.

**Comment by obelyaev** [comment]
Пробел действительно лучше делать вручную (просто ставить его в самом начале текста комментария), а проблему с английским я пофиксил.
