### ISSUE TITLE
Один и тот же Gombocz?

### ISSUE THREAD

**Issue by jvsntsn** [abaevdict/abaevdict#62]
![image](https://user-images.githubusercontent.com/48504970/63142014-a9014600-bff0-11e9-97b7-949290633fda.png)
Вот здесь тот же Gombocz, что забит в списке литературы? То есть я могу сослаться на него, а название книги дописать в текст ref'a?

**Comment by obelyaev** [comment]
Добавить в список литературы, там другой.

**Comment by obelyaev** [comment]
См. #46

**Comment by obelyaev** [comment]
Я думаю, лучше в таких случаях во всяком случае пока что не добавлять в список литературы, а писать этого Гомбоча в поле Author, а остальной текст — в поле Text. Дело в том, что эти ссылки встречаются очень часто. Для того, чтобы добавить новый элемент в список RefAbbrev, нужно лочить базу, т.е. это опять будет замедлять работу. В отличие от языков, здесь серьёзных проблем с переводом не возникает. Если все эти ссылки будут забиты как элемент ref, то не будет проблемы в дальнейшем по всем их пройти и при желании добавить в список литературы.
