### ISSUE TITLE
странное оформление примеров - все пихать в коммент? + названия языков

### ISSUE THREAD

**Issue by solanum-tuberosum** [abaevdict/abaevdict#63]
после значений идет какое-то пояснение где есть "=". просто записать в посткоммент?
дальше идут примеры, но без тире. Не помню, что мы делаем с таким. Записать в "коллокейшенс"?..

Еще проблемы с языками: авестийский, после него двоеточие и вообще + Перс. с большой буквы
![image](https://user-images.githubusercontent.com/13102259/64524950-5d4c6e80-d308-11e9-8c34-6c0e8015c3e4.png)

**Comment by obelyaev** [comment]
Я бы сделал просто примером, сделаю возможность переделывать пунктуацию.

**Comment by obelyaev** [comment]
Вообще, по идее, irux æzdaxun — это subentry, а вот то, что после, действительно, скорее пояснение / сравнение, потому что в иронском другое слово (æргом). Так что наверное это посткоммент действительно. Пунктуация — смотря как часто такой знак равенства встречается. Если редко, проще вручную написать.

Для авестийского пользуйтесь HideLanguage. Кстати, когда с большой буквы, тоже можно использовать этот трюк (написать с большой буквы, а потом выбрать и сделать HideLanguage).

**Comment by obelyaev** [comment]
См. слово irux — там всё сделано правильно (в скобках после перевода как PostComment).
