### ISSUE TITLE
īsdūg

### ISSUE THREAD

**Issue by solanum-tuberosum** [abaevdict/abaevdict#64]
Ссылка на исдуг, здесь просто u
![image](https://user-images.githubusercontent.com/13102259/64670284-378caa00-d46d-11e9-8f07-1f3fbca01546.png)

Но в других местах эта u очень выглядит как **ū**:
![image](https://user-images.githubusercontent.com/13102259/64670322-5db24a00-d46d-11e9-839c-99e913cf976b.png)
![image](https://user-images.githubusercontent.com/13102259/64670335-64d95800-d46d-11e9-8f04-7089dcea39bb.png)
![image](https://user-images.githubusercontent.com/13102259/64670395-99e5aa80-d46d-11e9-8c5d-a6a31ea2ec98.png)

Где как написать?
И вообще не странно, что одна иронская форма ссылается на другую?.. Может, это вообще какие-нибудь разные слова?.. В общем, я запуталась

**Comment by obelyaev** [comment]
Надо смотреть на то, как оно в словарной статье.

**Comment by obelyaev** [comment]
См. #75
