### ISSUE TITLE
пример, но без тире (не похоже на сабэнтри)

### ISSUE THREAD

**Issue by solanum-tuberosum** [abaevdict/abaevdict#65]
![image](https://user-images.githubusercontent.com/13102259/64713393-751d2180-d4c5-11e9-9d40-ee9333f2a954.png)
не запихнуть в посткоммент какой-то, потому что не получится вставить ссылку на литературу
не получится запихнуть в сабентри, потому что опять же явно это примеры со ссылкой на литературу
в пример не получается запихнуть потому что там почему-то нет тире!

**Comment by solanum-tuberosum** [comment]
ср. слово выше
![image](https://user-images.githubusercontent.com/13102259/64713576-c9c09c80-d4c5-11e9-8b6a-b4700f44e164.png)
здесь все нормально и тире есть. забить и положить в экзампл?

**Comment by solanum-tuberosum** [comment]
И здесь тоже не очень понимаю, как это все лучше записать...
![image](https://user-images.githubusercontent.com/13102259/64868404-f56b9000-d647-11e9-95ef-4b52d2293820.png)

**Comment by solanum-tuberosum** [comment]
тут тоже примеры вроде как, но без тире
![image](https://user-images.githubusercontent.com/13102259/64879147-fefff280-d65d-11e9-8637-b2a569994dcd.png)

**Comment by obelyaev** [comment]
Забить, пусть везде будет тире.

**Comment by solanum-tuberosum** [comment]
> И здесь тоже не очень понимаю, как это все лучше записать...
> ![image](https://user-images.githubusercontent.com/13102259/64868404-f56b9000-d647-11e9-95ef-4b52d2293820.png)

все-таки сделала здесь две пресабэнтри груп, вроде получилось как надо как раз
![image](https://user-images.githubusercontent.com/13102259/78016490-8c353b00-7353-11ea-85ef-f5efea35b7d4.png)
