### ISSUE TITLE
PreComment в example

### ISSUE THREAD

**Issue by jvsntsn** [abaevdict/abaevdict#66]
![image](https://user-images.githubusercontent.com/48504970/64904511-d581ae00-d6d3-11e9-8dba-3d2d6c569cc3.png)
пока запихнула в PostComment

**Comment by solanum-tuberosum** [comment]
У меня вот такое:
![image](https://user-images.githubusercontent.com/13102259/64920476-d8a69800-d7c0-11e9-9934-7f106bcc1a6a.png)
Пока тоже положила в посткоммент

**Comment by obelyaev** [comment]
Сделать PreComment к Example.

**Comment by solanum-tuberosum** [comment]
Еще один precomment в example!
![image](https://user-images.githubusercontent.com/13102259/66147869-591a2500-e618-11e9-9769-d0ebe5f2afa8.png)

**Comment by solanum-tuberosum** [comment]
Еще один прекоммент, слово kærʒyn
![image](https://user-images.githubusercontent.com/13102259/67224052-15f1eb80-f439-11e9-9a2a-623620f6df36.png)

**Comment by obelyaev** [comment]
Сделал PreComment к Example и поправил форматирование, чтобы всё работало (исправил только первый пример).
