### ISSUE TITLE
несоответствие переводов слова и употреблений в примерах?

### ISSUE THREAD

**Issue by jvsntsn** [abaevdict/abaevdict#67]
больше актуально для английской версии, наверное
во втором значении 'проводить' последний пример относится явно к не тому же 'проводить', что и остальные примеры, и по-английски там явно будет не spend?.. И нужно ли это попробовать как-то отразить в значениях слова? 
![image](https://user-images.githubusercontent.com/48504970/64904674-01059800-d6d6-11e9-802e-bde4fbc91913.png)

**Comment by obelyaev** [comment]
В английском на 1 перевод больше. Если пустой, то не отображать (ср. #53).

**Comment by obelyaev** [comment]
Сделал так, что пустой перевод исчезает, причём и в русском, и в английском, т.е. в принципе можно иметь и в английском на один перевод больше, если нужно.
