### ISSUE TITLE
недостающие ссылки на источники

### ISSUE THREAD

**Issue by jvsntsn** [abaevdict/abaevdict#7]
Евангелие от Матфея - странный предмет:
Вроде примеры оттуда есть,
А в списке источников его нет :)

**Comment by jvsntsn** [comment]
В этимологических ссылках еще нашла нечто под кодовым названием Gr. (на скрине) и не смогла сопоставить его ни с чем подходящим из списка...
![image](https://user-images.githubusercontent.com/48504970/55326963-afec4980-5491-11e9-97ad-436f141c3c95.png)

**Comment by obelyaev** [comment]
Это, как и Гюбшманн, указание автора при ссылке на журнал. Надо добавить поле Author в ссылке на источник.

**Comment by obelyaev** [comment]
Добавил Евангелие и автора.
