### ISSUE TITLE
ссылки при примерах

### ISSUE THREAD

**Issue by solanum-tuberosum** [abaevdict/abaevdict#71]
не помню, было такое ишью или нет
![image](https://user-images.githubusercontent.com/13102259/64918718-f7019900-d7aa-11e9-87fb-c2f11bc27938.png)
если я делаю посткоммент, то ссылка уезжает до перевода.
как такое оформлять?

**Comment by obelyaev** [comment]
См. #45

**Comment by solanum-tuberosum** [comment]
Вот еще пример странного посткоммента
![image](https://user-images.githubusercontent.com/13102259/66188240-78a06480-e68f-11e9-9a66-d5a2fbd39275.png)
Наверно, надо сделать отдельно Source и отдельно посткоммент? пока так и сделала (но посткоммент пока все еще не в нужном месте)

**Comment by solanum-tuberosum** [comment]
Еще один посткоммент в примере, где нужна запятая как разделитель
![image](https://user-images.githubusercontent.com/13102259/66190575-016dcf00-e695-11e9-9523-7d049db4e0f3.png)

**Comment by solanum-tuberosum** [comment]
![image](https://user-images.githubusercontent.com/13102259/67756062-63c6af00-fa4a-11e9-87ea-c4b7727bf82f.png)

**Comment by obelyaev** [comment]
> не помню, было такое ишью или нет
> ![image](https://user-images.githubusercontent.com/13102259/64918718-f7019900-d7aa-11e9-87fb-c2f11bc27938.png)
> если я делаю посткоммент, то ссылка уезжает до перевода.
> как такое оформлять?

Это Source, надо в таких случаях оставить аббревиатуру пустой и писать в поле Text.

**Comment by obelyaev** [comment]
> Вот еще пример странного посткоммента
> ![image](https://user-images.githubusercontent.com/13102259/66188240-78a06480-e68f-11e9-9a66-d5a2fbd39275.png)
> Наверно, надо сделать отдельно Source и отдельно посткоммент? пока так и сделала (но посткоммент пока все еще не в нужном месте)

Это вообще по идее PreComment к Source :) Я добавил, мне не жалко

**Comment by obelyaev** [comment]
Вроде бы здесь всё сделать можно.
