### ISSUE TITLE
ссылки на источники

### ISSUE THREAD

**Issue by jvsntsn** [abaevdict/abaevdict#8]
У меня в этимологических источниках встретился вот такой товарищ (первый, до аббревиатуры). Сейчас можно выбрать его с дополнительными поясняющими буковками, но тут-то он без буковок, наверное надо добавить его еще раз без всего?
![image](https://user-images.githubusercontent.com/48504970/55326603-d3fb5b00-5490-11e9-8af8-bae0c4c2b5d2.png)

**Comment by obelyaev** [comment]
Добавить просто Гюбшманна, без буковок.

**Comment by obelyaev** [comment]
На самом деле это тоже автор + источник, так что Гюбшманна пишем в Author и выбираем ZDMG в списке источников.
