### ISSUE TITLE
иронский и дигорский варианты

### ISSUE THREAD

**Issue by solanum-tuberosum** [abaevdict/abaevdict#9]
У дигорского слова есть sense, после этого встречается иронский вариант. Как это записывать?

![image](https://user-images.githubusercontent.com/13102259/55883302-c17ad300-5bae-11e9-998b-03b02887573c.png)
![image](https://user-images.githubusercontent.com/13102259/55883314-c8094a80-5bae-11e9-91c6-af7fc8906575.png)
![image](https://user-images.githubusercontent.com/13102259/55883327-cdff2b80-5bae-11e9-97d2-589c4f10f064.png)
![image](https://user-images.githubusercontent.com/13102259/55883344-d5263980-5bae-11e9-86fe-2cd2830c7991.png)
![image](https://user-images.githubusercontent.com/13102259/55883392-ed965400-5bae-11e9-8435-502cf355db07.png)
![image](https://user-images.githubusercontent.com/13102259/55883437-030b7e00-5baf-11e9-8265-4e6608937635.png)

**Comment by obelyaev** [comment]
Для таких случаев, видимо, лучше всего будет предусмотреть возможность добавлять xref после sense (в рамках какого-то контейнера типа SenseRef).

**Comment by solanum-tuberosum** [comment]
NB еще такие варианты
![image](https://user-images.githubusercontent.com/13102259/55886329-2d136f00-5bb4-11e9-8616-02a046a777d0.png)

**Comment by jvsntsn** [comment]
![image](https://user-images.githubusercontent.com/48504970/55887665-91373280-5bb6-11e9-8054-523b0f4d93dd.png)

**Comment by solanum-tuberosum** [comment]
![image](https://user-images.githubusercontent.com/13102259/55889854-651db080-5bba-11e9-858b-bbc549ddfe83.png)

**Comment by obelyaev** [comment]
Вроде бы все эти случаи описываются через PostComment внутри Sense (см., как сделано ǧaricund).
